apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-job"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "graph-backup"
    app.kubernetes.io/component: backup
spec:
  schedule: {{.Values.jobSchedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: graph-backup
              image: {{ .Values.image }}:{{ .Values.imageTag }}
              imagePullPolicy: Always
              env:
                - name: NEO4J_ADDR
                  value: {{ .Values.neo4jaddr }}
                - name: DATABASE
                  value: {{ .Values.database }}
                - name: CLOUD_PROVIDER
                  value: {{ .Values.cloudProvider }}
                - name: BUCKET
                  value: {{ .Values.bucket }}
                - name: HEAP_SIZE
                  value: {{ .Values.heapSize }}
                - name: PAGE_CACHE
                  value: {{ .Values.pageCache }}
                - name: FALLBACK_TO_FULL
                  value: "{{ .Values.fallbackToFull }}"
                - name: CHECK_CONSISTENCY
                  value: "{{ .Values.checkConsistency }}"
                - name: CHECK_INDEXES
                  value: "{{ .Values.checkIndexes }}"
                - name: CHECK_GRAPH
                  value: "{{ .Values.checkGraph }}"
                - name: CHECK_LABEL_SCAN_STORE
                  value: "{{ .Values.checkLabelScanStore }}"
                - name: CHECK_PROPERTY_OWNERS
                  value: "{{ .Values.checkPropertyOwners }}"
              volumeMounts:
                {{ if eq .Values.cloudProvider "aws" }}
                - name: aws-credentials
                  mountPath: /credentials/aws
                  readOnly: true
                {{ end }}
                {{ if eq .Values.cloudProvider "gcp" }}
                - name: gcp-credentials
                  mountPath: /credentials/gcp
                  readOnly: true
                {{ end }}
          volumes:
            {{ if eq .Values.cloudProvider "aws" }}
            - name: aws-credentials
              secret:
                secretName: {{ .Values.secretName }}
                items:
                  - key: credentials
                    path: credentials
            {{ end }}
            {{ if eq .Values.cloudProvider "gcp" }}
            - name: gcp-credentials
              secret:
                secretName: {{ .Values.secretName }}
                items:
                  - key: credentials.json
                    path: credentials.json
            {{ end }}