
= Overview

Neo4j-helm allows users to deploy multi-node Neo4j Enterprise Causal Clusters to Kubernetes instances, with configuration options for the most common scenarios. It represents a rapid way to get started running the world leading native graph database on top of Kubernetes.

This guide is intended only as a supplement to the Neo4j Operations Manual. Neo4j-helm is a docker container based deploy of Neo4j Causal Cluster. All of the information in the Operations Manual applies to its operation, and this guide will focus only on kubernetes-specific concerns.

[NOTE]
**In addition to the information in this user guide, a set of slides is available on the deployment architecture and chart structure of this repository. https://docs.google.com/presentation/d/14ziuwTzB6O7cp7fq0mA1lxWwZpwnJ9G4pZiwuLxBK70/edit?usp=sharing:[Neo4j Helm Chart Structure]**

== Versioning

The versioning of this helm chart will follow Neo4j versions for simplicity.

* Version 4.0.X-Y of the helm chart is compatible with Neo4j EE v4.0.*
* Version 4.1.X-Y of the helm chart is compatible with Neo4j EE v4.1.*
* (and so on)

The charts link:https://github.com/neo4j-contrib/neo4j-helm[in the GitHub repository] are for Neo4j 4.0 going forward. There are previous available charts for the Neo4j 3.5 series, but there are substantial differences between the two versions. Careful upgrade planning is advised before attempting to upgrade an existing chart.

Consult the https://neo4j.com/docs/operations-manual/current/upgrade/[upgrade guide] and expect that additional configuration of this chart will be necessary.

== Releases

link:https://github.com/neo4j-contrib/neo4j-helm/releases[Neo4j-Helm releases are downloadable via GitHub]

== Licensing

The source code to neo4j-helm is available under the terms of the Apache License, version 2.0.  See the LICENSE.txt file in the source code repository for full terms and conditions.

This documentation is licensed under link:{attachmentsdir}/LICENSE.txt[Creative Commons 4.0]

[NOTE]
The documentation version is v{docs-version}
