
[#neo4j_causal_cluster]
= Using with Neo4j Causal Cluster

[abstract]
--
This chapter describes considerations around using Neo4j Spark Connector with Neo4j Enterprise Causal Cluster.
--

== Overview

link:https://neo4j.com/docs/operations-manual/current/clustering/[Neo4j Clustering] is a feature available in
Enterprise Edition which allows high availability of the database through having multiple database members.

Neo4j Enterprise uses a link:https://neo4j.com/docs/operations-manual/current/clustering/introduction/#causal-clustering-introduction-operational[LEADER/FOLLOWER]
operational view, where writes are always processed by the leader, while reads can be serviced by either followers,
or optionally be read replicas, which maintain a copy of the database and serve to scale out read operations
horizontally.

== Remote Clients

Sometimes there will be remote applications that talk to Neo4j via official drivers, that want to use
streams functionality.  Best practices in these cases are:

* Always use a `neo4j+s://` driver URI when communicating with the cluster in the client application.
* Use link:https://neo4j.com/docs/driver-manual/current/sessions-transactions/#driver-transactions[Explicit Write Transactions] in
your client application when using procedure calls such as `CALL streams.consume` to ensure that the routing
driver routes the query to the leader.